export const exerciseNameSuggestions = [
  "Bench Press",
  "Incline Bench Press",
  "Dumbbell Bench Press",
  "Push Up",
  "Chest Fly",
  "Shoulder Press",
  "Lateral Raise",
  "Rear Delt Fly",
  "Triceps Pushdown",
  "Overhead Triceps Extension",
  "Pull Up",
  "Lat Pulldown",
  "Seated Row",
  "Barbell Row",
  "Single Arm Dumbbell Row",
  "Deadlift",
  "Barbell Curl",
  "Hammer Curl",
  "Back Squat",
  "Front Squat",
  "Leg Press",
  "Romanian Deadlift",
  "Walking Lunge",
  "Bulgarian Split Squat",
  "Hip Thrust",
  "Glute Bridge",
  "Standing Calf Raise",
  "Seated Calf Raise",
  "Plank",
  "Cable Crunch",
  "Hanging Knee Raise",
  "Ab Wheel Rollout",
] as const
